version: '3.7'

services:

  app:
    environment:
      NODE_ENV: development
      POSTGRES_HOST: db
    ports:
      - 127.0.0.1:3001:80

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - 127.0.0.1:5432:5432
