version: '2'

services:

  app:
    image: ${PROJECT_NAME}
    restart: always
    build:
      context: ../app/
    environment:
      NODE_ENV: development
    ports:
      - 127.0.0.1:8080:80

  db:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - 127.0.0.1:5432:5432
